# Generated by Django 4.2.4 on 2024-01-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Store Owner'), ('staff', 'Store Staff'), ('customer', 'Customer'), ('admin', 'admin')], max_length=10),
        ),
    ]
