# Generated by Django 4.2.4 on 2024-01-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Store Owner'), ('staff', 'Store Staff'), ('customer', 'Customer'), ('admin', 'admin')], max_length=10, null=True),
        ),
    ]
